Fosowl/agenticSeek

.gitignore
README.md
config.ini
main.py
prompts/casual_agent.txt
requirements.txt
sources/agent.py
sources/casual_agent.py
sources/code_agent.py
sources/interaction.py
sources/llm_provider.py
sources/memory.py
sources/router.py
sources/speech_to_text.py
sources/tools/BashInterpreter.py
sources/tools/flightSearch.py
sources/tools/tools.py
sources/tools/webSearch.py
sources/utility.py

Integrated the following features:
- Agent router -> select the best agent depending on user query using a one shot classification model. 
- Speech to text -> continuous listening of microphone with keyword trigger.
- Casual agent -> The default agent for basic conversation, capable of basic search on web or api

Integration of AI agent router, Speech to text, casual agent and basic web search tool.

---

README.md
config.ini
main.py
prompts/casual_agent.txt
prompts/manager_agent.txt
sources/interaction.py
sources/memory.py
sources/router.py
sources/speech_to_text.py
sources/text_to_speech.py
sources/utility.py

- Better doc string function documentation for all classes.
- Saving session working.
- Loading session working.
- Better prompt for casual agent.
- Minor fix for TTS and router system.

Better documentation & Session loading and recovery system

---

README.md
server/server_ollama.py
sources/agents/agent.py
sources/utility.py

Fixed issues:
KeyError: 'yello' #26
/server does not have stream_llm.py #23
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 603: character maps to <undefined> #25

Fix #23 #25 #26

---

config.ini
sources/agents/agent.py

make voice message gender neutral

"Please be patient sir" #32 fix

---

sources/llm_provider.py

Validate IP address only if it does not seem to be a domain

allow domains for provider_server_address

---

scripts/linux_install.sh
sources/text_to_speech.py

Use aplay for linux and install the dependency
afplay is only available for macos

linux text to speech

---

requirements.txt
sources/browser.py
sources/text_to_speech.py

updated the speak function , make it more sturctured , also added to play sound using afplay in macos and redirected linux or other to aplay , make sure the  display of audio  only work for jupyter notebooks not  in terminal. the name of audio file is directly used in code , standerized it.  Auto chromedriver version update and automatic finding of chromedriver path.

Update text_to_speech.py ,  browser.py .

---

start_services.cmd

1. start ollam provider
2. up docker

Add: windows version start_services

---

README.md
README_CHT.md

Mod README

---

README.md
README_FR.md

readme update

---

README.md
README_CHS.md

add CHS readme

---

.gitignore
prompts/base/casual_agent.txt
prompts/base/coder_agent.txt
prompts/base/planner_agent.txt
prompts/jarvis/casual_agent.txt
prompts/jarvis/coder_agent.txt
prompts/jarvis/planner_agent.txt
sources/agents/browser_agent.py
sources/agents/planner_agent.py
sources/browser.py
sources/interaction.py
sources/llm_provider.py
sources/memory.py
sources/speech_to_text.py
sources/text_to_speech.py

- Example in casual agent prompt file would cause small <32b model to hallucinate that it was a previous task
- Add handling of numerical values with get_text() for browser agent
- better tests at end of file
- Improve some docstring
- Fixed various bug

Fix various bug + handle webpage numerical value + improve prompts.

---

main.py
prompts/base/coder_agent.txt
prompts/base/planner_agent.txt
prompts/jarvis/planner_agent.txt
server/app.py
server/sources/cache.py
server/sources/generator.py
server/sources/ollama_handler.py
sources/agents/browser_agent.py
sources/agents/casual_agent.py
sources/agents/code_agent.py
sources/agents/file_agent.py
sources/agents/planner_agent.py
sources/browser.py
sources/interaction.py
sources/language.py
sources/llm_provider.py
sources/logger.py
sources/memory.py
sources/router.py
sources/text_to_speech.py
sources/tools/searxSearch.py
sources/tools/tools.py
tests/test_browser_agent_parsing.py

- improved web navigation agent with proper readme format reading of webpage and prompt improvement and more verbose
- improve planner agent so it can pass multiple previous agent output to an agent 
- logging system
- test added for browser agent parsing function

Enhanced web navigation & planner agent + logging system

---

CONTRIBUTING.md
server/install.sh
sources/agents/browser_agent.py
sources/agents/casual_agent.py
sources/agents/code_agent.py
sources/agents/file_agent.py
sources/agents/planner_agent.py
sources/llm_provider.py
sources/router.py

self.role. of agents didn't need to be a lang: role dict since we change how we deal with prompt that aren't in english.
better contributing.md with technical explanation

Refactor self.role for new multilingual router + contributing.md

---

README.md
README_CHS.md
README_CHT.md
api.py
frontend/agentic-seek-front/src/App.js
sources/agents/agent.py
sources/browser.py
sources/llm_provider.py
sources/router.py
sources/schemas.py

update discord link in all readme + merging small change i made on front/back

Update readme and slight frontend fix attempt

---

frontend/agentic-seek-front/public/index.html
frontend/agentic-seek-front/src/App.css
frontend/agentic-seek-front/src/App.js
frontend/agentic-seek-front/src/colors.js
sources/browser.py

- Integrate new frontend design by @Saminu to main
- Randomize user agent for web navigation.

Integrate new frontend + random user agent

---

README.md
README_CHS.md
README_CHT.md
README_FR.md
README_JP.md
frontend/agentic-seek-front/src/App.css
frontend/agentic-seek-front/src/App.js
prompts/base/planner_agent.txt
sources/agents/agent.py
sources/agents/browser_agent.py
sources/agents/planner_agent.py
sources/browser.py

Planner agent adapt over time to previous task results.
Browser agent has new callback to prevent looping over same link.
Temporary remove background task section of the frontend, so expand chat/computer sections.
Update readme

Planner agent improvement, Browser agent stuck prevention, frontend change, readme update + fix

---

sources/tools/mcp_finder.py

Add MCP finder tool that use https://smithery.ai/docs/registry
No other MCP tool for now, a friend of mine will work on MCP tools and agent for MCP

Feat : MCP finder tool

---

prompts/base/file_agent.txt
prompts/base/planner_agent.txt
prompts/jarvis/planner_agent.txt
sources/agents/browser_agent.py
sources/agents/code_agent.py
sources/agents/planner_agent.py
sources/llm_provider.py
sources/router.py
sources/tools/BashInterpreter.py
sources/tools/GoInterpreter.py
sources/tools/fileFinder.py
sources/tools/mcpFinder.py
sources/tools/safety.py
sources/tools/tools.py

- Less confusing, better prompt for planner
- Planner can use casual agent between task
- Show next task on frontend
- Logger system for all agents.

Planner agent improvements

---

start_services.sh

fix issue : Support docker compose #137

fix : start_services.sh not supporting newest docker compose (#137)

---

sources/llm_provider.py

I have a dedicated Ollama machine running in my network. 
This change allows you to connect to a local as well as a remote Ollama server. 
Connecting to a local server is unchanged, but for a remote Ollama connection, change the config.ini to for example:
```
[MAIN]
is_local = False
provider_name = ollama
provider_model = deepseek-r1:32b
provider_server_address = 192.168.0.25:11434
```
The Ollama server should be listening for network connections:
```$ OLLAMA_HOST=0.0.0.0 ollama serve```

Allow connecting to a remote Ollama server

---

frontend/agentic-seek-front/src/App.js
sources/browser.py

Fix #175 + make browser view wider

Fix connection issue with 0.0.0.0 in app.js + more wide browser view

---

api.py
cli.py
frontend/agentic-seek-front/package-lock.json
frontend/agentic-seek-front/package.json
frontend/agentic-seek-front/src/App.css
frontend/agentic-seek-front/src/App.js
scripts/linux_install.sh
scripts/macos_install.sh
sources/browser.py
sources/web_scripts/inject_safety_script.js
sources/web_scripts/spoofing.js

Improve browser stealthness, bypass more antibot
Markdown support for frontend
Improved linux & macos install script
Fix green used for command failure on frontend
No allow cross origin everything

Better browser fingerprint spoofing + Markdown support for frontend + block color display fix

---

.dockerignore

I've Added a standard .dockerignore file here for the smoother functionality helping the individuals who are quite new with docker so that it won't heavy load their images with files that are not necessary.

Added Docker Ignore file.

---

README_CHS.md
README_CHT.md
README_FR.md

* Modify the README title in Simplified Chinese
* Modify README in different languages ​​to use a unified logo

Edit README.md

---

README_ES.md

This PR adds comprehensive Spanish documentation to the AgenticSeek project, making it more accessible to Spanish-speaking users and contributors. The translation maintains the technical accuracy and formatting of the original English documentation while ensuring natural language flow in Spanish.
- Translated the main README.md to Spanish (README_ES.md)
- Maintained all code blocks, links, and formatting
- Preserved technical terms and commands in their original form
- Ensured consistent terminology throughout the translation
- Kept all badges, images, and special formatting intact
- Spanish is one of the most widely spoken languages globally
- It will help expand the project's reach to Spanish-speaking developers
- It follows the project's goal of being accessible to a diverse community …

Add README in Spanish including installation, configuration and use

---

.env.example
docker-compose.yml
scripts/windows_install.bat
sources/tools/searxSearch.py

High priority fix for internet connection issue on docker

Fix : searxng search issue on docker

---

README.md

This PR significantly improves the ChromeDriver troubleshooting section in the README to help users resolve common version compatibility issues, especially in Docker environments.
- **Enhanced Root Cause Analysis**: Explains why Docker + stealth mode bypasses volume mounts
- **Chrome for Testing API**: Clear instructions for Chrome 115+ using the official testing dashboard  
- **Step-by-Step Solutions**: Detailed installation methods with command examples
- **Docker-Specific Guidance**: Highlights the project root directory approach for stealth mode compatibility
- **Troubleshooting Tips**: Log checking, version verification, and debugging steps
- **Version Compatibility Matrix**: Practical examples of working Chrome/ChromeDriver combinations
Users frequently encounter …

docs: enhance ChromeDriver troubleshooting for Docker environments

---

README.md

OLLAMA_HOST should be set to 0.0.0.0 to ensure it work with docker.

fix : update readme for correct ollama start
